% -------------------------------------------------------------------
%  Generated by MATLAB on 25-Oct-2023 14:27:23
%  MATLAB version: 9.14.0.2337262 (R2023a) Update 5
% -------------------------------------------------------------------
saveVarsMat = load('trial1.mat');

ans = 0;

fid = 3;

hex_values = saveVarsMat.hex_values; % <65536x2 char> too many elements

i = 65536;

img = saveVarsMat.img; % <256x256 uint8> too many elements

pixel_values = saveVarsMat.pixel_values; % <256x256 uint8> too many elements

clear saveVarsMat;
